### ISSUE TITLE
Change winlibs from UCRT version

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/spbuild#13]
Per discussion in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/56#issuecomment-1448281793 and onwards.

We need to update the URL at 
https://github.com/StrawberryPerl/spbuild/blob/68d953d38b667553dc176a7fb65d2e5c65df4aee/5.34/Dockerfile#L18

While we are at it, it might be useful to change the unpacked dir from ```/z/mingw64``` to something like ```/z/winlibs``` to avoid confusion with ```/mingw64```.  This is one line in the docker file but will need other parts of the system to be updated.  
https://github.com/StrawberryPerl/spbuild/blob/68d953d38b667553dc176a7fb65d2e5c65df4aee/5.34/Dockerfile#L26

**Comment by genio** [comment]
Apologies, @shawnlaffan. It seems like I didn't have the permissions setup correctly on this repo for you to be able to commit, etc. Hopefully that's fixed now

**Comment by shawnlaffan** [comment]
All good.  I haven't tried to push to this repo yet in any case.
