### ISSUE TITLE
msys2_shell_830_64.bat doesn't see z: drive

### ISSUE THREAD

**Issue by plicease** [StrawberryPerl/spbuild#4]
Running the .bat file gives me this:

```
PS Z:\build-extlibs> .\msys2_shell_830_64.bat
The system cannot find the drive specified.
```

I wasn't able to run command.com, but cmd.exe works: 

```
PS Z:\build-extlibs> cmd.exe
Microsoft Windows [Version 10.0.17763.864]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\spbuild\build-extlibs>set GCCDIR=z:\mingw64bit.830

C:\spbuild\build-extlibs>set CMAKEBIN=z:\sw\cmake\bin

C:\spbuild\build-extlibs>set NASMBIN=z:\sw\nasm

C:\spbuild\build-extlibs>set PATH=%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%GCCDIR%\bin;%CMAKEBIN%;%NASMBIN%

C:\spbuild\build-extlibs>z:\msys64\msys2_shell.cmd -use-full-path
The system cannot find the drive specified.

C:\spbuild\build-extlibs>z:
The system cannot find the drive specified.
```

even though the z: drive seems to be visible from PowerShell, whatever trickery is done to create the z: drive doesn't seem to be visible by cmd.exe.  So probably either need to rework trickery in z: drive or port sys2_shell_830_64.bat etc to PowerShell scripts.

**Comment by genio** [comment]
I think the problem with not seeing the Z drive is now corrected. Can you give it another go?

**Comment by plicease** [comment]
Will try it again tomorrow.

**Comment by genio** [comment]
This is fixed. Though there are now other issues
