### ISSUE TITLE
README.md: remove command prompts?

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/spbuild#8]
The command prompts in the readme mean the code cannot be copied and pasted into a terminal.  

It would perhaps be useful if the call location were noted in the preceding text instead.

e.g.:

Let's build and run our container (call from the powershell).
```PowerShell
git clone https://github.com/StrawberryPerl/spbuild.git .
cd .\spbuild\5.34
docker build -t strawberryperl/strawbuild:latest -t strawberryperl/strawbuild:5.34 .
docker run --rm -it strawberryperl/strawbuild:latest powershell.exe
```

I can easily work up a PR if needed.

**Comment by genio** [comment]
Yeah, I had it like that at one point. It got a bit weird to keep up with which environment the user should be in at the given time, so I showed the entirety to hopefully keep that clear. I'm certainly not married to the way it is at the moment

**Comment by shawnlaffan** [comment]
Maybe the working directory can be listed as a comment (in addition to stating which shell to use in the general text), e.g.:

```PowerShell
#  PS C:\Users\genio> 
git clone https://github.com/StrawberryPerl/spbuild.git .
cd .\spbuild\5.34
# PS C:\Users\genio\spbuild\5.34> 
docker build -t strawberryperl/strawbuild:latest -t strawberryperl/strawbuild:5.34 .
docker run --rm -it strawberryperl/strawbuild:latest powershell.exe
```

```bash
#  ContainerAdministrator@767e415f72ad MINGW64 /z/extlib
./build.sh 5034 __
```

**Comment by genio** [comment]
That sounds good to me!

**Comment by genio** [comment]
Thank you for cleaning that up (and, well, everything you've been doing)!

**Comment by shawnlaffan** [comment]
Not a problem.  Hopefully it brings a new release that bit closer.
